---
  .travis.yml:
    .travis.yml:
      script: "\"bundle exec rake validate && bundle exec rake test SPEC_OPTS='--format documentation'\""
      includes:
      - rvm: 1.9.3
        env: PUPPET_GEM_VERSION="~> 3.1.0"
      - rvm: 1.9.3
        env: PUPPET_GEM_VERSION="~> 3.2.0"
      - rvm: 1.9.3
        env: PUPPET_GEM_VERSION="~> 3.3.0"
      - rvm: 1.9.3
        env: PUPPET_GEM_VERSION="~> 3.4.0"
      - rvm: 1.9.3
        env: PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES="yes"
      - rvm: 1.9.3
        env: PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES="yes"
      - rvm: 1.9.3
        env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES="yes"
      - rvm: 2.0.0
        env: PUPPET_GEM_VERSION="~> 3.2.0"
      - rvm: 2.0.0
        env: PUPPET_GEM_VERSION="~> 3.3.0"
      - rvm: 2.0.0
        env: PUPPET_GEM_VERSION="~> 3.4.0"
      - rvm: 2.0.0
        env: PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES="yes"
      - rvm: 2.0.0
        env: PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES="yes"
      - rvm: 2.0.0
        env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES="yes"
      - rvm: 2.1.0
        env: PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES="yes"
      - rvm: 2.1.0
        env: PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES="yes"
      - rvm: 2.1.0
        env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES="yes"
    hc_secure: "CK11caPkzorkB4onwQPDolAFM32RO+Mn/rt3MRBe0xkt+SyRj8Icmv4MLbWUhiIydZQLrZpC+k993U9RuNOgghOcBq9tKF3U1sM6rrWLNJOnvobi6S+WZYe325IcsMchREERd0TUJYeYWCw2YxYlJBS/xRmpXO5gLZAPzm1NI9k="
  spec/acceptance/nodesets/centos-65-x64.yml:
    delete: true
  spec/acceptance/nodesets/ubuntu-server-1204-x64.yml:
    delete: true
