---
language: ruby
cache: bundler
bundler_args: --without system_tests development
script: "bundle exec rake validate && bundle exec rake test SPEC_OPTS='--format documentation'"
sudo: false
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.3.0" RAKE_GEM_VERSION="~> 10.5.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0" RAKE_GEM_VERSION="~> 10.5.0" FUTURE_PARSER="yes"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.3.0" JSON_PURE_GEM_VERSION="~> 2.0.1"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0" JSON_PURE_GEM_VERSION="~> 2.0.1" FUTURE_PARSER="yes"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 4.1"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 4.2"
